# Generated by Django 6.1.1 on 2026-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.flaticon.com/free-icon/placeholder_1377194', max_length=500),
        ),
    ]
