# Generated by Django 6.1.1 on 2026-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/1377/1377194.png', max_length=500),
        ),
    ]
